# Generated by Django 2.2.5 on 2019-09-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealizadorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_de_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=50)),
                ('funcao', models.CharField(max_length=30)),
            ],
        ),
    ]
